#!/bin/bash
# generate_disk_configs v0.0.2 last mod 2016/02/26
# Latest version at <https://github.com/kenanrizvic/xen-backup-scripts>
# Copyright  2016 Kenan Rizvic <kenan.rizvic@gmail.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#    General Public License <gnu.org/licenses/gpl.html> for more details.
#
#-------------------------------------------------------------------------------
reldir=`dirname $0`
cd $reldir
directory=`pwd`
echo start creation of file   $disk_list_for_tar in directory $directory
. ./config
echo virtual machine $vm_name which is placed  on /dev/mapper/$lvm_group-$vm_name
echo notice: this script doesnt take lvm volumes for swap if named so
echo \#lvm       \#exclude fajl > $disk_list_for_tar
echo \#lvm        > $disk_list_for_dd
virsh domblklist $vm_name | grep $lvm_group | awk -F$lvm_group/ '{print $2}' |grep -v swap | grep -v -e '^$' >> $disk_list_for_tar
virsh domblklist $vm_name | grep $lvm_group | awk -F$lvm_group/ '{print $2}' |grep -v swap | grep -v -e '^$' >> $disk_list_for_dd
echo contents of  file $disk_list_for_tar is
echo ----start--------
cat $disk_list_for_tar
echo ---end of fle -------
echo please exclude ones which you do not want to go to tar file backup with settings second column to be file with exclude patterns in form of
echo ./dir1
echo ./dir2
echo content of file   $disk_list_for_dd is
echo ----start--------
cat $disk_list_for_dd
echo ----end of file-----
echo plase check manualy list , excldue swap if speretae disk is used
