#!/bin/bash
# send_backup_to_remote v0.0.2 last mod 2016/02/26
# Latest version at <https://github.com/kenanrizvic/xen-backup-scripts>
# Copyright  2016 Kenan Rizvic <kenan.rizvic@gmail.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#    General Public License <gnu.org/licenses/gpl.html> for more details.
#
#-------------------------------------------------------------------------------
reldir=`dirname $0`
cd $reldir
directory=`pwd`
echo starting in  $directory sending files with extensions tgz xml cfg log txt config to dest backup loc

. ./config

if [ ! -d $dir_source ]; then
mkdir $dir_source
fi

mount -t $backup_type $backup_location_details $dir_source
if [ $? -ne 0 ]; then
echo echo mounting or missing sudo privilege for mount 
rmdir $dir_source
exit 1
fi

rsync -rvlt *.tgz $dir_source/$dir_destination/
rsync -rvlt *.xml $dir_source/$dir_destination/
rsync -rvlt *.cfg $dir_source/$dir_destination/ 
rsync -rvlt *.log $dir_source/$dir_destination/
rsync -rvlt *.txt $dir_source/$dir_destination/
rsync -rvlt config $dir_source/$dir_destination/
umount $dir_source
if [ $? -ne 0 ]; then
echo error when umounting or missing sudo privilege
exit 1
fi
rmdir $dir_source
