#!/bin/bash
# start_vm v0.0.2 last mod 2016/02/26
# Latest version at <https://github.com/kenanrizvic/xen-backup-scripts>
# Copyright  2016 Kenan Rizvic <kenan.rizvic@gmail.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#    General Public License <gnu.org/licenses/gpl.html> for more details.
#
#-------------------------------------------------------------------------------

# Usage string
appname=`basename $0`
USAGE="Usage: ${appname} -m <vmaschine> " 

# check if anything is on commandline
let $# || { echo you havent set parameters $USAGE ; exit 1; }  # Exit if no arguments

# Handle incoming arguments
while getopts :m: opt
do
    case $opt in
    m) vm_name=$OPTARG ;;
   \?) 	echo "Sorry no such option, please try again" ;
echo $USAGE;
 exit 1;;
*)
        # Should not occur
          echo "Unknown error while processing options"
          ;;
	
esac
done


echo Starting  $vm_name
virsh start $vm_name
echo Status:
virsh dominfo $vm_name | grep State | grep -v  "shut off"
if [ $? -ne 0 ]; then
echo error starting domU
echo starting again
virsh start $vm_name
fi
echo Status:
virsh dominfo $vm_name | grep State | grep -v "shut off"
if [ $? -ne 0 ]; then
echo error when starting machine please check
exit 1
fi

